# Generated by Django 5.0.4 on 2024-04-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_utilisateur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='youssef@gmail.com', max_length=254, unique=True)),
                ('telephone', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ncni', models.CharField(max_length=100, null=True)),
                ('alergie', models.CharField(blank=True, choices=[('alimentaires', 'Alimentaires'), ('animal', 'Animal')], max_length=20)),
                ('Toute_demande', models.CharField(max_length=500, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('Nombre_de_personnes', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.utilisateur')),
            ],
        ),
    ]
