# Generated by Django 5.0.4 on 2024-04-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_logins_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logins',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
