# Generated by Django 5.0.4 on 2024-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, default='youssef@gmail.com', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Nombre_de_personnes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Toute_demande',
        ),
        migrations.RemoveField(
            model_name='client',
            name='alergie',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ncni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
    ]
