# Generated by Django 5.0.4 on 2024-04-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_reservation', '0002_auth_remove_client_nombre_de_personnes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Nombre_de_personnes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Toute_demande',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='alergie',
            field=models.CharField(blank=True, choices=[('alimentaires', 'Alimentaires'), ('animal', 'Animal')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='ncni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App_reservation.auth'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(default='youssef@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='auth',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
